### ISSUE TITLE
Setup deployment to OSSRH 

### ISSUE THREAD

**Issue by jvanzyl** [oneops/boo#1]
We need to create a ticket with [OSSRH][1] so that OneOps related projects can deploy to the `com.oneops` namespace in Maven Central. Once that is done we can do a release and update the README.md to point to Maven Central instead of Walmart's internal Nexus instance.

[1]: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by mosabua** [comment]
I can take care of that tomorrow if you want @jvanzyl

**Comment by jvanzyl** [comment]
I made the initial entry, but I did it for all Walmart groupIds: https://issues.sonatype.org/browse/OSSRH-29050

**Comment by mosabua** [comment]
I added some further proof of ownership and asked for details about why Joel did not yet proceed.

**Comment by mosabua** [comment]
Both of us are set up to do a release. Do you want me to do that? What version?

**Comment by mosabua** [comment]
Should be all ready to deploy. I did a couple of snapshot deployments with the new release profile successfully. Only potential issue is unit test failure..

**Comment by mosabua** [comment]
Works now and @jvanzyl cut the 1.0.2 release successfully. http://repo1.maven.org/maven2/com/oneops/boo/boo/1.0.2/
