### ISSUE TITLE
Can not add platform-to-platform link

### ISSUE THREAD

**Issue by jayeshpise** [oneops/boo#19]
It is not possible to specify platform-to-platform dependency in boo yml.

For example: In an application, a Tomcat platform may depend on db. In such case, first db platform needs to be deployed and then tomcat platform. 

In oneops, you can define this dependency manually. Boo needs to be able to let user do so through boo yml

**Comment by khushbulohia** [comment]
https://github.com/oneops/boo/pull/25 the feature has been added in boo
