### ISSUE TITLE
Provide an ability to update for auto healing flag/options

### ISSUE THREAD

**Issue by khushbulohia** [oneops/boo#32]
Boo doesn't support update of **auto replace**, **auto replace** and **auto scale** flags
Provide an ability to update these auto healing flag/options

**Comment by jdillon** [comment]
Boo doesn't support the initial setting of this too not just the update correct?  Both should be added yes?

**Comment by khushbulohia** [comment]
yes both cases are handled

**Comment by khushbulohia** [comment]
Sample config for auto-healing
`environment: # Only support one environment for now.
  global_dns: 'true'
  availability: 'redundant'
  platforms:
    tomcat:
      auto_healing:
        autorepair: false
        autoreplace: true
        replace_after_minutes: 60
        replace_after_repairs: 4`

**Comment by khushbulohia** [comment]
released feature in http://repo1.maven.org/maven2/com/oneops/boo/boo/1.0.11/
