### ISSUE TITLE
Unit test failure on Linux and OSX

### ISSUE THREAD

**Issue by mosabua** [oneops/boo#5]
Currently I get the failure below on my environment:

```
$ mvn -v
Apache Maven 3.5.0-beta-1 (214540c2ae5431645bb927d6dc5498ebafc27359; 2017-03-20T09:58:41-07:00)
Maven home: /opt/tools/apache-maven-3.5.0-beta-1
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-66-generic", arch: "amd64", family: "unix"
```

Maven log output

```
Running com.oneops.boo.ClientConfigInterpolatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.26 sec
Running com.oneops.boo.ClientConfigProcessorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.857 sec
Running com.oneops.boo.TestPlatformBeanBuilder
[main] INFO com.oneops.boo.BooTest - Using config file file:/media/sf_dev/github/oneops/boo/target/test-classes/test.yaml
[main] ERROR com.oneops.boo.BooTest - ProvisionException: Fatal error Unable to provision, see the following errors:

1) Error in custom provider, com.fasterxml.jackson.databind.JsonMappingException: Expected a field name (Scalar value in YAML), got this instead: <org.yaml.snakeyaml.events.MappingStartEvent(anchor=null, tag=null, implicit=true)>
 at [Source: java.io.StringReader@446293d; line: 83, column: 6]
 at [Source: java.io.StringReader@446293d; line: 83, column: 5] (through reference chain: com.oneops.boo.yaml.Yaml["environment"])
  at com.oneops.boo.JaywayHttpModule.getOoInstance(JaywayHttpModule.java:126)
  while locating com.oneops.client.api.OOInstance

1 error, quit!

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.849 s
[INFO] Finished at: 2017-03-24T11:45:09-07:00
[INFO] Final Memory: 32M/312M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project boo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by mosabua** [comment]
On the other hand it seems to work for @jvanzyl on OSX. @jayeshpise reports also problems with this test.

**Comment by mosabua** [comment]
Same problem exists with Maven 3.3.9 on the same machine.

**Comment by jvanzyl** [comment]
I'll try your version of the JDK.

**Comment by jvanzyl** [comment]
You still getting this failure @mosabua?

**Comment by mosabua** [comment]
I will test again tomorrow. I just had a thought too.. it might be due to my setup of running on a VM (Ubuntu) one a mounted drive from OSX. Causes weird issues sometimes with native IO stuff - although for Boo that doesnt really make sense.. but its worth checking out.

**Comment by mosabua** [comment]
I move the codebase to my VM (Ubuntu) and still get failures. Also fails on OSX btw. 

Details for OSX test: 

mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /opt/tools/apache-maven-3.3.9
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"


-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.oneops.boo.ClientConfigInterpolatorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.139 sec - in com.oneops.boo.ClientConfigInterpolatorTest
Running com.oneops.boo.ClientConfigProcessorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.254 sec - in com.oneops.boo.ClientConfigProcessorTest
Running com.oneops.boo.TestPlatformBeanBuilder

Results :

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:07 min
[INFO] Finished at: 2017-04-17T10:42:36-07:00
[INFO] Final Memory: 41M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project boo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /opt/tmp/boo && /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/bin/java -jar /opt/tmp/boo/target/surefire/surefirebooter383763876257206900.jar /opt/tmp/boo/target/surefire/surefire6052751379150132744tmp /opt/tmp/boo/target/surefire/surefire_07956985658760155112tmp
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by mosabua** [comment]
with -X -e on Linux I get

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.764 s
[INFO] Finished at: 2017-04-17T09:59:13-07:00
[INFO] Final Memory: 27M/297M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project boo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/manfred/dev/github/oneops/boo && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/manfred/dev/github/oneops/boo/target/surefire/surefirebooter1155033862609934731.jar /home/manfred/dev/github/oneops/boo/target/surefire/surefire5982919372264273406tmp /home/manfred/dev/github/oneops/boo/target/surefire/surefire_03043264797728621562tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project boo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/manfred/dev/github/oneops/boo && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/manfred/dev/github/oneops/boo/target/surefire/surefirebooter1155033862609934731.jar /home/manfred/dev/github/oneops/boo/target/surefire/surefire5982919372264273406tmp /home/manfred/dev/github/oneops/boo/target/surefire/surefire_03043264797728621562tmp
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/manfred/dev/github/oneops/boo && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/manfred/dev/github/oneops/boo/target/surefire/surefirebooter1155033862609934731.jar /home/manfred/dev/github/oneops/boo/target/surefire/surefire5982919372264273406tmp /home/manfred/dev/github/oneops/boo/target/surefire/surefire_03043264797728621562tmp
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/manfred/dev/github/oneops/boo && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/manfred/dev/github/oneops/boo/target/surefire/surefirebooter1155033862609934731.jar /home/manfred/dev/github/oneops/boo/target/surefire/surefire5982919372264273406tmp /home/manfred/dev/github/oneops/boo/target/surefire/surefire_03043264797728621562tmp
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:590)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by mosabua** [comment]
I will have to look into what that test actually does I think...

**Comment by mosabua** [comment]
I am reopening this issue. I just created a Looper build and see the same problem.

**Comment by mosabua** [comment]
mvn -v
Apache Maven 3.5.1 (094e4e31a5af55bb17be87675da41d9aeca062f3; 2017-09-10T05:42:54-07:00)
Maven home: /opt/tools/apache-maven-3.5.1
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-96-generic", arch: "amd64", family: "unix"

**Comment by ictinc** [comment]
Hi there, 
I know this thread is quite old however I'm receiving the same error on GCP Ubuntu 18.04. I followed the exact documentation as outlined on oneops.com.

root@oneops:/opt/oneops# javac -version
javac 1.8.0_181

root@oneops:/opt/oneops# mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /opt/apache-maven
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1021-gcp", arch: "amd64", family: "unix"

I'm getting the following:
Results :

Failed tests:
com.oneops.controller.workflow.DeployerTest.(com.oneops.controller.workflow.DeployerTest)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project controller: There are test failures.
[ERROR]
[ERROR] Please refer to /opt/oneops/controller/target/surefire-reports for the individual test results.

Should oneops work on a virtual server?

Any idea what I could be doing different to solve this?

**Comment by vinayrao92** [comment]
@mosabua  @jvanzyl : This happened to me today. The error is independent of the platform. 
It basically occurs because jackson is trying to parse an invalid yaml file.

The file `test.yaml` which is used in these 2 test classes namely `TestPlatformBeanBuilder` & `TestPlatformBeanHelper` expects these default profile variables (host, organization , api_key, email, 
cloud)
If a user does not have these 'default' profile variables configured with dummy values OR if the `~/.boo/config`file does NOT exist, jackson databind fails & these errors are thrown.
The `JsonMappingException` is thrown from this line `mapper.readValue(yaml, Yaml.class)`  at `com.oneops.boo.BooYamlReader`.

I think we need to create this file in looper flow as well for the tests to run.
Since this is already mentioned in the [readme file](https://github.com/oneops/boo/blob/master/README.md)  easiest option would be to assume that the user provides this file.

I thought a simple validation of [config map](https://github.com/oneops/boo/blob/master/src/main/java/com/oneops/boo/BooConfigInterpolator.java) would fix it, but then i believe not all 5 keys are mandatory since the user may just hard code them in the provided .yaml file.

Please let me know your thoughts.

**Comment by vinayrao92** [comment]
@mosabua : Please let me know if this builds in looper since i do not have looper running locally. (Hopefully it will build :))
